### ISSUE TITLE
Is this project dead or alive?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [luyangkenneth/quickshift-redux#2]
Ever wonder why not one person has installed it since you uploaded it to the Chrome Store over 6 months ago?

Well the lack of a screenshot might not be the _only_ reason,  but it may be the _main_ reason.
And the fact that it no longer seems to be under development is another.

If it's dead, it should be removed from the C.S.

**Comment by luyangkenneth** [comment]
Hello there! You're right, this project isn't under active development. It could definitely be a more feature-rich extension. But I think that while the functionality is extremely simple, it still does one job well and I personally use it everyday. It seems that there're at least 46 other users (at the time of writing this) using it too. 

Thanks for reminding me about the lack of marketing on the chrome web store. I'm actually a little stuck on this - do you have any suggestions on how I could capture the idea of shifting tabs via a screenshot?

Cheers mate! :beer:

**Comment by GitTheHellOutaHere** [comment]
I don't use the app so I can't help - I've never even seen it since there are no screenshots.

Yesterday I was browsing for extensions to rearrange/organize tabs when your listing came up.
