### ISSUE TITLE
Default move shortcuts hijack Alt-shift-left/right (text selection shortcuts)

### ISSUE THREAD

**Issue by ptim** [luyangkenneth/quickshift-redux#4]
Hi! Still loving this extension, tx 👍 

I was using the suggested default keys (ctrl+shift+left/right) for move right/left, but found that alt+shift+left/right would also trigger the move command, rather than the default...

Repro:
- set default move keys
- focus the location bar
- hit alt+shift+left
- text selection doesn't change, tab is moved left

Workaround: use ctrl+left/right 

Couldn't see why, from glancing at the source.. maybe a Chrome glitch <shrug />

Cheers! ptim

**Comment by luyangkenneth** [comment]
Hey thanks for the bug report! Yeah this happened to me too, right after I upgraded to Chrome 69 :/ So I've been living with this issue myself for a while now. I don't think there's much I can do about it, so I'm glad that you managed to find a workaround!

**Comment by ptim** [comment]
No worries - unfortunately the workaround I was using started to demonstrate the same issue, so I've switched to `ctrl + ,`  & `ctrl + .` - text navigation seems uninterrupted now  👍 

I'll close because we've got a workaround...
