### ISSUE TITLE
Emphasize features on Chrome Web Store

### ISSUE THREAD

**Issue by Semmu** [luyangkenneth/quickshift-redux#5]
Hi!

I just want to tell you that this extension is awesome and I use it on all my machines, **BUT** I always have trouble finding/installing it, since its not really optimized for SEO. I know this may sound dumb, but you should really emphasize that this extension can move tabs between windows, since its a killer feature other extensions don't really provide. Yet when I'm searching for "chrome move tabs between windows" on Google it simply doesn't list this extension, which should be #1 in my opinion.

(This just happened to me today: I wanted to install this extension at my workplace, but I simply couldn't find it, while I knew that I have this installed at home. I just did not remember its name and Google doesn't know about it either.)

So I suggest updating the Chrome Web Store description so people can find it easier.

Thanks for the extension again!

**Comment by luyangkenneth** [comment]
Thanks for pointing this out! I'm glad you find this extension useful 🙂 I've [updated the description](https://chrome.google.com/webstore/detail/quickshift-redux-rearrang/daiohbdbfnmpbolhbpbngdjdjcbclikm) and added more visuals while I was at it. I don't know if this will help much with SEO, but let's see how it goes.
