### ISSUE TITLE
ctrl-shift-M opens my chrome user google accouint settings

### ISSUE THREAD

**Issue by sticker592** [luyangkenneth/quickshift-redux#8]
It doesn't move tabs between windows for me. And the personalize hotkeys is not available when I open the settings:
<img width="227" alt="user settings" src="https://user-images.githubusercontent.com/9032644/76717410-e352d300-66f8-11ea-97c9-fca633d5c9ff.png">
<img width="265" alt="no hotkey" src="https://user-images.githubusercontent.com/9032644/76717415-e948b400-66f8-11ea-8ae9-db99cff77d8b.png">

**Comment by luyangkenneth** [comment]
Hi! You're probably on Windows, which is why the default hotkeys didn't work in this case.

It seems like you went to this specific extension's settings, which isn't the place to modify your keyboard shortcuts. To do that, go to chrome://extensions/shortcuts instead.

**Comment by sticker592** [comment]
That was it. THanks!
